string = input("Please type in your Text:")
words = 0
sentences = 0
letters = 0

for x in string:
    if(x=="." or x=="!" or x=="?"):
        sentences += 1
        continue
    if(x==" "):
        words+=1
        continue
    else:
        letters+=1
        continue
words += 1

# print("Sätze", sentences)
# print("wröter", words)
# print("buchstaben", letters)

averageLettersPerWord = letters / words * 100
averageSentencesPerWord = sentences / words * 100
L = averageLettersPerWord
S = averageSentencesPerWord # Just to make the formola look easy. no need to save bytes
formula = 0.0588 * L - 0.296 * S - 15.8

x = round(formula)

if x < 1:
    print("Before Grade 1")
elif x > 15:
    print("Grade 16+")
else:
    print("Grade ", x)


# Results for cs50/problems/2023/x/sentimental/readability generated by check50 v3.3.7
# :) readability.py exists.
# :( handles single sentence with multiple words
#     expected "Grade 7\n", not "Grade  8\n"
# :( handles punctuation within a single sentence
#     expected "Grade 9\n", not "Grade  10\n"
# :( handles more complex single sentence
#     expected "Grade 8\n", not "Grade  9\n"
# :) handles multiple sentences
# :) handles multiple more complex sentences
# :) handles longer passages
# :) handles questions in passage
# :) handles reading level before Grade 1
# :) handles reading level at Grade 16+
# Idk where my error is at